server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: art-generator-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# API Configuration
google:
  api-key: "AIzaSyAW1Ee5bvqLSH4Z_ylxvWarwDAIeHgXj0I"
  gemini:
    base-url: "https://generativelanguage.googleapis.com/v1beta"
    model: "gemini-2.0-flash-exp"
  imagen:
    model: "imagen-3-generate-001"

imagekit:
  url: "https://ik.imagekit.io"
  public-key: "your_public_key_here"
  private-key: "your_private_key_here"
  url-endpoint: "https://ik.imagekit.io/your_id"

cloudinary:
  cloud-name: "your_cloud_name"
  api-key: "your_api_key"
  api-secret: "your_api_secret"

logging:
  level:
    com.artgenerator: DEBUG
    org.springframework.web: DEBUG